# Generated by Django 4.2.3 on 2023-07-29 12:12

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
