# Generated by Django 4.2.3 on 2023-08-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_is_popular_article_related_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
