# Generated by Django 4.2.3 on 2023-07-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
