# Generated by Django 4.2.3 on 2023-08-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', through='shop.BookCategory', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
