# Generated by Django 4.2.3 on 2023-08-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'Is in progress'), ('waiting_for_payment', 'Is waiting for payment'), ('in_delivery', 'Was sent'), ('completed', 'Is completed'), ('canceled', 'Was canceled')], default='in_progress', max_length=100),
        ),
    ]
